blank_issues_enabled: false
contact_links:
  - name: CubeDev Discord
    url: https://discord.gg/papermc
    about: If you are having trouble with config, come and ask us in `#weaponmechanics-support`